import Head from 'next/head'
import PresentationDesk from '../pages/PresentationDesk'
import Presentation_mob from '../pages/Presentation_mob'

export default function Home() {
  return (
    <div>
      <Head>
        <title>EL Encanto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <PresentationDesk />

        <Presentation_mob />
      </main>

      
    </div>
  )
}
